// this file will be eventually generated by AWIG feature

module __relu_dpi;

    export "DPI-C" function dpi_read_reg;
    export "DPI-C" function dpi_write_reg;

    function byte dpi_read_reg;
        input int hid;
        input int sel;
        begin
            $error("[dpi-read-reg] invalid hid");
        end
    endfunction

    function void dpi_write_reg;
        input int hid;
        input int sel;
        input byte value;
        begin
            $error("[dpi-write-reg] invalid hid");
        end
    endfunction

endmodule
