// this file will be eventually generated by AWIG feature

module __Relu_dpi;

    export "DPI-C" function dpi_read_reg;
    export "DPI-C" function dpi_write_reg;

    function byte dpi_read_a;
        input int sel;
        reg [8-1:0] data;
        begin
            data = __Relu.dut.a;
            return data[sel*8 +: 8];
        end
    endfunction

    function void dpi_write_a;
        input int sel;
        input byte value;
        reg [8-1:0] data;
        begin
            data = __Relu.dut.a;
            data[sel*8 +: 8] = value;
            __Relu.dut.a = data;
        end
    endfunction

    function byte dpi_read_y;
        input int sel;
        reg [8-1:0] data;
        begin
            data = __Relu.dut.y;
            return data[sel*8 +: 8];
        end
    endfunction

    function void dpi_write_y;
        input int sel;
        input byte value;
        reg [8-1:0] data;
        begin
            data = __Relu.dut.y;
            data[sel*8 +: 8] = value;
            __Relu.dut.y = data;
        end
    endfunction

    function byte dpi_read_reg;
        input int hid;
        input int sel;
        begin
            if (hid == 0) begin
                return dpi_read_a(sel);
            end
            else if (hid == 1) begin
                return dpi_read_y(sel);
            end
            else begin
                $error("[dpi-read-reg] invalid hid");
            end
        end
    endfunction

    function void dpi_write_reg;
        input int hid;
        input int sel;
        input byte value;
        begin
            if (hid == 0) begin
                dpi_write_a(sel, value);
            end
            else if (hid == 1) begin
                dpi_write_y(sel, value);
            end
            else begin
                $error("[dpi-write-reg] invalid hid");
            end
        end
    endfunction

endmodule
